### ISSUE TITLE
[Bug]: Failed to open IDTA 02017-1-0_Template_Asset Interfaces Description.aasx

### ISSUE THREAD

**Issue by ZiqiangXu11** [rwth-iat/aas_manager#24]
### Contact Details

ziqiang.xu@omron.com

### What happened?

When open published IDTA 02017-1-0_Template_Asset Interfaces Description.aasx from IDTA, an error happened.

### Relevant log output

```shell
Following is the detail error message.
---------------------------------------------
Traceback (most recent call last):
  File "basyx\aas\adapter\aasx.py", line 142, in read_into
IndexError: list index out of range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "aas_editor\widgets\treeview_pack.py", line 496, in openPack
  File "aas_editor\package.py", line 35, in __init__
  File "aas_editor\package.py", line 84, in _read
  File "basyx\aas\adapter\aasx.py", line 144, in read_into
ValueError: Not a valid AASX file: aasx-origin Relationship is missing.
```

**Comment by zrgt** [comment]
@ZiqiangXu11 Sorry for the long response. I guess the problem occures because of the bug in submodel-template aasx file referenced here: https://github.com/eclipse-aaspe/aaspe/issues/161

There is a tool which can fix the problem: https://github.com/LukasBenner/AASFix

**Comment by ZiqiangXu11** [comment]
@zrgt 
Hi, thanks for looking into this issue.
After fixing the AID submodel template by AASFix,  error still happened when open it by AASManager.

-------------------------------------
Traceback (most recent call last):
  File "basyx\aas\adapter\xml\xml_deserialization.py", line 287, in _failsafe_construct
  File "basyx\aas\adapter\xml\xml_deserialization.py", line 722, in construct_submodel_element
  File "basyx\aas\adapter\xml\xml_deserialization.py", line 959, in construct_submodel_element_list
  File "<frozen _collections_abc>", line 1099, in extend
  File "<frozen _collections_abc>", line 1078, in append
  File "basyx\aas\model\base.py", line 2105, in insert
  File "basyx\aas\model\base.py", line 1886, in add
  File "basyx\aas\model\base.py", line 1926, in _execute_item_add_hook
  File "basyx\aas\model\submodel.py", line 760, in _check_constraints
basyx.aas.model.base.AASConstraintViolation: All first level elements must be of the type specified in type_value_list_element=SubmodelElement, got ReferenceElement (Constraint AASd-108)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "basyx\aas\adapter\xml\xml_deserialization.py", line 287, in _failsafe_construct
  File "basyx\aas\adapter\xml\xml_deserialization.py", line 722, in construct_submodel_element
  File "basyx\aas\adapter\xml\xml_deserialization.py", line 931, in construct_submodel_element_collection
  File "basyx\aas\adapter\xml\xml_deserialization.py", line 333, in _failsafe_construct_multiple
  File "basyx\aas\adapter\xml\xml_deserialization.py", line 291, in _failsafe_construct
ValueError: Failed to construct {https://admin-shell.io/aas/3/0}submodelElementList on line 235 using construct_submodel_element!

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "basyx\aas\adapter\xml\xml_deserialization.py", line 287, in _failsafe_construct
  File "basyx\aas\adapter\xml\xml_deserialization.py", line 722, in construct_submodel_element
  File "basyx\aas\adapter\xml\xml_deserialization.py", line 931, in construct_submodel_element_collection
  File "basyx\aas\adapter\xml\xml_deserialization.py", line 333, in _failsafe_construct_multiple
  File "basyx\aas\adapter\xml\xml_deserialization.py", line 291, in _failsafe_construct
ValueError: Failed to construct {https://admin-shell.io/aas/3/0}submodelElementCollection on line 171 using construct_submodel_element!

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "basyx\aas\adapter\xml\xml_deserialization.py", line 287, in _failsafe_construct
  File "basyx\aas\adapter\xml\xml_deserialization.py", line 1033, in construct_submodel
  File "basyx\aas\adapter\xml\xml_deserialization.py", line 333, in _failsafe_construct_multiple
  File "basyx\aas\adapter\xml\xml_deserialization.py", line 291, in _failsafe_construct
ValueError: Failed to construct {https://admin-shell.io/aas/3/0}submodelElementCollection on line 47 using construct_submodel_element!

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "aas_editor\widgets\treeview_pack.py", line 496, in openPack
  File "aas_editor\package.py", line 35, in __init__
  File "aas_editor\package.py", line 84, in _read
  File "basyx\aas\adapter\aasx.py", line 151, in read_into
  File "basyx\aas\adapter\aasx.py", line 194, in _read_aas_part_into
  File "basyx\aas\adapter\aasx.py", line 224, in _parse_aas_part
  File "basyx\aas\adapter\xml\xml_deserialization.py", line 1471, in read_aas_xml_file
  File "basyx\aas\adapter\xml\xml_deserialization.py", line 1438, in read_aas_xml_file_into
  File "basyx\aas\adapter\xml\xml_deserialization.py", line 333, in _failsafe_construct_multiple
  File "basyx\aas\adapter\xml\xml_deserialization.py", line 291, in _failsafe_construct
ValueError: Failed to construct {https://admin-shell.io/aas/3/0}submodel on line 27 using construct_submodel!

**Comment by zrgt** [comment]
@ZiqiangXu11 

Unfortunately the bug is still on the side of submodel-template. It violates some constraint and that'why AAS Manager can not construct the submodel.

I have already opened the issue for the template here: https://github.com/admin-shell-io/submodel-templates/issues/62

Probably you can fix the problem following these steps:
- open AASX file with some Archive programm (e.g. WINrar) 
- open file `\aasx\AAS_Template_for_AID\AAS_Template_for_AID.aas.xml` in archive 
- replace "SubmodelElement" with "ReferenceElement" on line 2706.
- Save changes
